import { User } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Chen',
    email: 'alex.chen@example.com',
    age: 24,
    skills: ['React', 'Node.js', 'TypeScript', 'UI/UX Design'],
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    bio: 'Full-stack developer passionate about building impactful products. Looking for a co-founder to start a fintech startup.',
    location: 'San Francisco, CA',
    experience: '3 years',
    interests: ['Startups', 'AI/ML', 'Fintech', 'Web3'],
    lookingFor: 'co-founder',
    availability: 'full-time',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    age: 26,
    skills: ['Product Management', 'Market Research', 'Data Analysis', 'Growth Hacking'],
    profilePhoto: 'https://images.unsplash.com/photo-1494790108755-2616b93a3dea?w=400&h=400&fit=crop&crop=face',
    bio: 'Product manager with experience in B2B SaaS. Love turning ideas into successful products that users love.',
    location: 'Austin, TX',
    experience: '4 years',
    interests: ['Product Strategy', 'User Research', 'Analytics', 'SaaS'],
    lookingFor: 'project-collaborator',
    availability: 'part-time',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'Marcus Rodriguez',
    email: 'marcus.r@example.com',
    age: 22,
    skills: ['Python', 'Machine Learning', 'Data Science', 'Computer Vision'],
    profilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    bio: 'CS student specializing in AI/ML. Built several computer vision projects and looking for hackathon teammates.',
    location: 'Boston, MA',
    experience: '2 years',
    interests: ['AI/ML', 'Robotics', 'Computer Vision', 'Research'],
    lookingFor: 'hackathon-partner',
    availability: 'weekends',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'Emma Thompson',
    email: 'emma.t@example.com',
    age: 28,
    skills: ['Digital Marketing', 'Brand Strategy', 'Content Creation', 'Social Media'],
    profilePhoto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    bio: 'Marketing strategist with 5+ years helping startups grow. Looking to join an early-stage team as a co-founder.',
    location: 'New York, NY',
    experience: '5 years',
    interests: ['Marketing', 'Branding', 'Growth', 'Content Strategy'],
    lookingFor: 'co-founder',
    availability: 'full-time',
    createdAt: new Date('2024-01-08'),
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.k@example.com',
    age: 25,
    skills: ['iOS Development', 'Swift', 'Mobile UI/UX', 'App Store Optimization'],
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    bio: 'Mobile app developer with 4+ apps in the App Store. Passionate about creating beautiful, user-friendly mobile experiences.',
    location: 'Seattle, WA',
    experience: '3 years',
    interests: ['Mobile Development', 'Design', 'Gaming', 'AR/VR'],
    lookingFor: 'project-collaborator',
    availability: 'flexible',
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '6',
    name: 'Lisa Park',
    email: 'lisa.p@example.com',
    age: 27,
    skills: ['Blockchain', 'Solidity', 'DeFi', 'Smart Contracts'],
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face',
    bio: 'Blockchain developer passionate about DeFi and Web3. Looking for like-minded developers to build the future of finance.',
    location: 'Miami, FL',
    experience: '2 years',
    interests: ['Blockchain', 'Cryptocurrency', 'DeFi', 'Web3'],
    lookingFor: 'co-founder',
    availability: 'full-time',
    createdAt: new Date('2024-01-18'),
  },
];

export const commonSkills = [
  'JavaScript', 'TypeScript', 'React', 'Vue.js', 'Angular', 'Node.js', 'Python', 'Java',
  'Swift', 'Kotlin', 'Flutter', 'React Native', 'UI/UX Design', 'Figma', 'Adobe Creative Suite',
  'Product Management', 'Project Management', 'Agile', 'Scrum', 'Digital Marketing', 'SEO',
  'Data Science', 'Machine Learning', 'AI', 'Blockchain', 'Smart Contracts', 'DevOps',
  'AWS', 'Docker', 'Kubernetes', 'GraphQL', 'REST APIs', 'Database Design', 'PostgreSQL',
  'MongoDB', 'Firebase', 'Git', 'Testing', 'CI/CD', 'Business Development', 'Sales',
  'Content Writing', 'Social Media Marketing', 'Brand Strategy', 'Market Research'
];

export const interests = [
  'Startups', 'Entrepreneurship', 'Technology', 'AI/ML', 'Web3', 'Blockchain', 'Fintech',
  'Healthcare Tech', 'EdTech', 'Climate Tech', 'Social Impact', 'Gaming', 'AR/VR',
  'IoT', 'Cybersecurity', 'Data Analytics', 'Cloud Computing', 'Mobile Apps', 'SaaS',
  'E-commerce', 'Marketplace', 'Consumer Products', 'B2B Solutions', 'Developer Tools'
];